#!/usr/bin/env python3
"""Embed config.jsonc and style.css as C string defaults."""

import sys


def c_string(text: str) -> str:
    out = ['"']
    for ch in text:
        o = ord(ch)
        if ch == '"':
            out.append('\\"')
        elif ch == '\\':
            out.append('\\\\')
        elif ch == '\n':
            out.append('\\n')
        elif ch == '\r':
            out.append('\\r')
        elif ch == '\t':
            out.append('\\t')
        elif o < 0x20 or o == 0x7F:
            out.append('\\%03o' % o)
        else:
            out.append(ch)
    out.append('"')
    return ''.join(out)


def main() -> int:
    if len(sys.argv) != 4:
        print('usage: gen_defaults.py config.jsonc style.css defaults.h',
              file=sys.stderr)
        return 1
    config_path, css_path, out_path = sys.argv[1], sys.argv[2], sys.argv[3]
    with open(config_path, 'r', encoding='utf-8') as f:
        config = f.read()
    with open(css_path, 'r', encoding='utf-8') as f:
        css = f.read()
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write('// Generated by scripts/gen_defaults.py; do not edit.\n')
        f.write('#ifndef MANGOBAR_DEFAULTS_H\n')
        f.write('#define MANGOBAR_DEFAULTS_H\n\n')
        f.write('static const char default_config_jsonc[] =\n    ')
        f.write(c_string(config))
        f.write(';\n\n')
        f.write('static const char default_style_css[] =\n    ')
        f.write(c_string(css))
        f.write(';\n\n')
        f.write('#endif\n')
    return 0


if __name__ == '__main__':
    sys.exit(main())
